ssh:
  - host: github.com
  - host: "*.hrntknr.net"
  - host: "*"
    commands:
      - cat
      - ls
      - kubectl get
k8s:
  - cluster: pear
    mode: rw
  - cluster: test
    mode: rw
  - cluster: "*"
    mode: r
